# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa15228ecd40a5c25250f45020bb2d2579195df240db10966680af7015e82b969d6cc01e8400aca2d28f8ffd3a963149b3c9e564913ee216bd12519f9b37772

test:
  secret_key_base: d7d102d4fcd6bde967bd3615b3a7202b57cde3c338254fecf0b01d302625a9114a71290ee35ee4444c2f90218f5d17f85ca0ae5b0892924f4064f48b4fc7fe06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
