# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b5ca3a6af83312e020dd0d051ff710532eea13d4b395041b1632dd9b2356edc770d6b18b2a7d12a088c8a424aad2faf107691415892f8a46f30e4fbf314d951

test:
  secret_key_base: a298e4aa69cc736f48915a4bb5bb1745b70c21a66606ffbbfb861b3d156a3e49879b51fd1bdf9780240c0b953dea2a132cb28fbfafb4c335012fce474d0b670e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
